livros = [
    {"titulo": "Dom Casmurro", "autor": "Machado de Assis", "ano": 1899},
    {"titulo": "A Hora da Estrela", "autor": "Clarice Lispector", "ano": 1977},
    {"titulo": "O Cortiço", "autor": "Aluísio Azevedo", "ano": 1890},
    {"titulo": "Orçamento sem falhas", "autor": "Nath Finanças", "ano": 2021},
    {"titulo": "Minha Sombria Vanessa", "autor": "Kate Elizabeth Russell", "ano": 2020},
    {"titulo": "Recursão", "autor": "Blake Crouch", "ano": 2020},
    {"titulo": "M, o Filho do Século", "autor": "Antonio Scurati", "ano": 2020},
    {"titulo": "Oblivion Song: Entre Dois Mundos", "autor": "Robert Kirkman", "ano": 2020},
    {"titulo": "Não se humilha, não", "autor": "Isabela Freitas", "ano": 2020},
    {"titulo": "Os segredos que guardamos", "autor": "Lara Prescott", "ano": 2020},
    {"titulo": "Baby Shark!", "autor": "Stevie Lewis", "ano": 2020},
    {"titulo": "A Guerra Pela Uber", "autor": "Mike Isaac", "ano": 2020},
    {"titulo": "Cidade nas Trevas", "autor": "Adam Christopher", "ano": 2020},
    {"titulo": "Território Lovecraft", "autor": "Matt Ruff", "ano": 2020},
    {"titulo": "A última porta", "autor": "Scott Cawthon", "ano": 2020},
    {"titulo": "A Última Festa (e-Book)", "autor": "Lucy Foley", "ano": 2020},
    {"titulo": "Uma chance de lutar", "autor": "Elizabeth Warren", "ano": 2020},
    {"titulo": "Uma Dor Tão Doce", "autor": "David Nicholls", "ano": 2020},
    {"titulo": "Este é o Mar", "autor": "Mariana Enriquez", "ano": 2020},
    {"titulo": "A Última Festa", "autor": "Lucy Foley", "ano": 2020},
    {"titulo": "Coragem", "autor": "Raina Telgemeier", "ano": 2020},
    {"titulo": "A Convenção das Aves", "autor": "Ransom Riggs", "ano": 2020},
    {"titulo": "Como o Cérebro Cria", "autor": "David Eagleman", "ano": 2020},
    {"titulo": "1793", "autor": "Niklas Natt och Dag", "ano": 2020},
    {"titulo": "Território Lovecraft", "autor": "Matt Ruff", "ano": 2020},
    {"titulo": "Para Todos os Garotos que Já Amei", "autor": "Jenny Han", "ano": 2020},
    {"titulo": "P.S.: Ainda Amo Você", "autor": "Jenny Han", "ano": 2020},
    {"titulo": "O Livro de Líbero", "autor": "Alfredo Nugent Setubal", "ano": 2020},
    {"titulo": "Terra Americana", "autor": "Jeanine Cummins", "ano": 2020},
    {"titulo": "Você não merece ser feliz", "autor": "Daniel Furlan", "ano": 2020},
    {"titulo": "O Livro De Líbero", "autor": "Alfredo Nugent Setubal", "ano": 2020},
    {"titulo": "Princípios Para O Sucesso", "autor": "Ray Dalio", "ano": 2020},
    {"titulo": "Black Hammer (Vol #4)", "autor": "Jeff Lemire", "ano": 2020},
    {"titulo": "A Convenção Das Aves", "autor": "Ransom Riggs", "ano": 2020},
    {"titulo": "As Outras Pessoas", "autor": "C.J. Tudor", "ano": 2020},
    {"titulo": "Uma Dor Tão Doce", "autor": "David Nicholls", "ano": 2020},
    {"titulo": "A Grande Gripe", "autor": "John M. Barry", "ano": 2020},
    {"titulo": "The Outsiders", "autor": "S. E. Hinton", "ano": 2020},
    {"titulo": "SuperNormal", "autor": "Greg James", "ano": 2020}
]
#